# This file is used to run the services in a private docker network.
# The back-end is not exposed to the host (no ports: key), it will be accessible only 
# from the front-end and/or other service in the same Docker network
# created automatically by docker-compose.
# Back-end is accessible from the front-end using the service name 'backend'
# and the Dokcer network will resolve the service name to the IP address of 
# the back-end service. 

version: '3.8'

services:
  backend:
    image: fastapi-app
    environment:
      - PORT=8080
    #expose:
    #  - 8080      

  frontend:
    image: streamlit-app
    ports:
      - "${FRONTEND_PORT:-8051}:8051"
    environment:
      - PORT=${FRONTEND_PORT:-8051}
      - ENDPOINT_URL=http://backend:8080/classify
    depends_on:
      - backend
